/*
 * File: app/view/TestViewport.js
 *
 * This file was generated by Sencha Architect version 3.5.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 6.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 6.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('CKEditorExtSix.view.TestViewport', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.testviewport',

    requires: [
        'CKEditorExtSix.view.TestViewportViewModel',
        'Ext.form.field.TextArea'
    ],

    viewModel: {
        type: 'testviewport'
    },

    layout: {
        type: 'vbox',
        align: 'center',
        pack: 'center'
    },
    items: [
        {
            xtype: 'ckeditor',
            height: 368,
            width: 790,
            fieldLabel: ''
        }
    ]

});